#!/bin/bash

# DYLD_LIBRARY_PATH="$(dirname $0)/../lib" $0.bin "$@"

export DYLD_LIBRARY_PATH="`dirname "$0"`/../lib/"
# Workaround for macosx gatekeeper, see https://github.com/arduino/Arduino/issues/3468
chmod +x "`dirname "$0"`/dfu-util-bin"
"`dirname "$0"`/dfu-util-bin" -l -d $2 -a $3 -s $4 -D $5
"`dirname "$0"`/dfu-util-bin" -l -d $2 -a $3 --reset-stm32
